set SynModuleInfo {
  {SRCNAME pynqrypt_encrypt_Pipeline_1 MODELNAME pynqrypt_encrypt_Pipeline_1 RTLNAME pynqrypt_encrypt_pynqrypt_encrypt_Pipeline_1
    SUBMODULES {
      {MODELNAME pynqrypt_encrypt_flow_control_loop_pipe_sequential_init RTLNAME pynqrypt_encrypt_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME pynqrypt_encrypt_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME pynqrypt_encrypt_Pipeline_2 MODELNAME pynqrypt_encrypt_Pipeline_2 RTLNAME pynqrypt_encrypt_pynqrypt_encrypt_Pipeline_2}
  {SRCNAME aes_generate_round_keys_Pipeline_1 MODELNAME aes_generate_round_keys_Pipeline_1 RTLNAME pynqrypt_encrypt_aes_generate_round_keys_Pipeline_1}
  {SRCNAME aes_generate_round_keys_Pipeline_loop_generate_round_keys MODELNAME aes_generate_round_keys_Pipeline_loop_generate_round_keys RTLNAME pynqrypt_encrypt_aes_generate_round_keys_Pipeline_loop_generate_round_keys
    SUBMODULES {
      {MODELNAME pynqrypt_encrypt_aes_generate_round_keys_Pipeline_loop_generate_round_keys_crypto_aes_sbox_ROMbkb RTLNAME pynqrypt_encrypt_aes_generate_round_keys_Pipeline_loop_generate_round_keys_crypto_aes_sbox_ROMbkb BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pynqrypt_encrypt_aes_generate_round_keys_Pipeline_loop_generate_round_keys_crypto_aes_rcon_ROMcud RTLNAME pynqrypt_encrypt_aes_generate_round_keys_Pipeline_loop_generate_round_keys_crypto_aes_rcon_ROMcud BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME aes_generate_round_keys MODELNAME aes_generate_round_keys RTLNAME pynqrypt_encrypt_aes_generate_round_keys}
  {SRCNAME ctr_encrypt_Pipeline_1 MODELNAME ctr_encrypt_Pipeline_1 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_1}
  {SRCNAME ctr_encrypt_Pipeline_2 MODELNAME ctr_encrypt_Pipeline_2 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_2}
  {SRCNAME aes_encrypt_block_Pipeline_loop_aes_encrypt_block MODELNAME aes_encrypt_block_Pipeline_loop_aes_encrypt_block RTLNAME pynqrypt_encrypt_aes_encrypt_block_Pipeline_loop_aes_encrypt_block
    SUBMODULES {
      {MODELNAME pynqrypt_encrypt_aes_encrypt_block_Pipeline_loop_aes_encrypt_block_crypto_aes_sbox_ROM_AUTO_1R RTLNAME pynqrypt_encrypt_aes_encrypt_block_Pipeline_loop_aes_encrypt_block_crypto_aes_sbox_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME aes_encrypt_block_Pipeline_2 MODELNAME aes_encrypt_block_Pipeline_2 RTLNAME pynqrypt_encrypt_aes_encrypt_block_Pipeline_2}
  {SRCNAME aes_encrypt_block MODELNAME aes_encrypt_block RTLNAME pynqrypt_encrypt_aes_encrypt_block
    SUBMODULES {
      {MODELNAME pynqrypt_encrypt_aes_encrypt_block_temp_RAM_AUTO_1R1W RTLNAME pynqrypt_encrypt_aes_encrypt_block_temp_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block}
  {SRCNAME ctr_encrypt_Pipeline_4 MODELNAME ctr_encrypt_Pipeline_4 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_4}
  {SRCNAME ctr_encrypt_Pipeline_5 MODELNAME ctr_encrypt_Pipeline_5 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_5}
  {SRCNAME ctr_encrypt_Pipeline_6 MODELNAME ctr_encrypt_Pipeline_6 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_6}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block1 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block1 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block1}
  {SRCNAME ctr_encrypt_Pipeline_8 MODELNAME ctr_encrypt_Pipeline_8 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_8}
  {SRCNAME ctr_encrypt_Pipeline_9 MODELNAME ctr_encrypt_Pipeline_9 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_9}
  {SRCNAME ctr_encrypt_Pipeline_10 MODELNAME ctr_encrypt_Pipeline_10 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_10}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block2 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block2 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block2}
  {SRCNAME ctr_encrypt_Pipeline_12 MODELNAME ctr_encrypt_Pipeline_12 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_12}
  {SRCNAME ctr_encrypt_Pipeline_13 MODELNAME ctr_encrypt_Pipeline_13 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_13}
  {SRCNAME ctr_encrypt_Pipeline_14 MODELNAME ctr_encrypt_Pipeline_14 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_14}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block3 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block3 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block3}
  {SRCNAME ctr_encrypt_Pipeline_16 MODELNAME ctr_encrypt_Pipeline_16 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_16}
  {SRCNAME ctr_encrypt_Pipeline_17 MODELNAME ctr_encrypt_Pipeline_17 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_17}
  {SRCNAME ctr_encrypt_Pipeline_18 MODELNAME ctr_encrypt_Pipeline_18 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_18}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block4 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block4 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block4}
  {SRCNAME ctr_encrypt_Pipeline_20 MODELNAME ctr_encrypt_Pipeline_20 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_20}
  {SRCNAME ctr_encrypt_Pipeline_21 MODELNAME ctr_encrypt_Pipeline_21 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_21}
  {SRCNAME ctr_encrypt_Pipeline_22 MODELNAME ctr_encrypt_Pipeline_22 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_22}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block5 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block5 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block5}
  {SRCNAME ctr_encrypt_Pipeline_24 MODELNAME ctr_encrypt_Pipeline_24 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_24}
  {SRCNAME ctr_encrypt_Pipeline_25 MODELNAME ctr_encrypt_Pipeline_25 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_25}
  {SRCNAME ctr_encrypt_Pipeline_26 MODELNAME ctr_encrypt_Pipeline_26 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_26}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block6 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block6 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block6}
  {SRCNAME ctr_encrypt_Pipeline_28 MODELNAME ctr_encrypt_Pipeline_28 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_28}
  {SRCNAME ctr_encrypt_Pipeline_29 MODELNAME ctr_encrypt_Pipeline_29 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_29}
  {SRCNAME ctr_encrypt_Pipeline_30 MODELNAME ctr_encrypt_Pipeline_30 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_30}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block7 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block7 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block7}
  {SRCNAME ctr_encrypt_Pipeline_32 MODELNAME ctr_encrypt_Pipeline_32 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_32}
  {SRCNAME ctr_encrypt_Pipeline_33 MODELNAME ctr_encrypt_Pipeline_33 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_33}
  {SRCNAME ctr_encrypt_Pipeline_34 MODELNAME ctr_encrypt_Pipeline_34 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_34}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block8 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block8 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block8}
  {SRCNAME ctr_encrypt_Pipeline_36 MODELNAME ctr_encrypt_Pipeline_36 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_36}
  {SRCNAME ctr_encrypt_Pipeline_37 MODELNAME ctr_encrypt_Pipeline_37 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_37}
  {SRCNAME ctr_encrypt_Pipeline_38 MODELNAME ctr_encrypt_Pipeline_38 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_38}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block9 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block9 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block9}
  {SRCNAME ctr_encrypt_Pipeline_40 MODELNAME ctr_encrypt_Pipeline_40 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_40}
  {SRCNAME ctr_encrypt_Pipeline_41 MODELNAME ctr_encrypt_Pipeline_41 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_41}
  {SRCNAME ctr_encrypt_Pipeline_42 MODELNAME ctr_encrypt_Pipeline_42 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_42}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block10 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block10 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block10}
  {SRCNAME ctr_encrypt_Pipeline_44 MODELNAME ctr_encrypt_Pipeline_44 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_44}
  {SRCNAME ctr_encrypt_Pipeline_45 MODELNAME ctr_encrypt_Pipeline_45 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_45}
  {SRCNAME ctr_encrypt_Pipeline_46 MODELNAME ctr_encrypt_Pipeline_46 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_46}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block11 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block11 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block11}
  {SRCNAME ctr_encrypt_Pipeline_48 MODELNAME ctr_encrypt_Pipeline_48 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_48}
  {SRCNAME ctr_encrypt_Pipeline_49 MODELNAME ctr_encrypt_Pipeline_49 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_49}
  {SRCNAME ctr_encrypt_Pipeline_50 MODELNAME ctr_encrypt_Pipeline_50 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_50}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block12 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block12 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block12}
  {SRCNAME ctr_encrypt_Pipeline_52 MODELNAME ctr_encrypt_Pipeline_52 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_52}
  {SRCNAME ctr_encrypt_Pipeline_53 MODELNAME ctr_encrypt_Pipeline_53 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_53}
  {SRCNAME ctr_encrypt_Pipeline_54 MODELNAME ctr_encrypt_Pipeline_54 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_54}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block13 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block13 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block13}
  {SRCNAME ctr_encrypt_Pipeline_56 MODELNAME ctr_encrypt_Pipeline_56 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_56}
  {SRCNAME ctr_encrypt_Pipeline_57 MODELNAME ctr_encrypt_Pipeline_57 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_57}
  {SRCNAME ctr_encrypt_Pipeline_58 MODELNAME ctr_encrypt_Pipeline_58 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_58}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block14 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block14 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block14}
  {SRCNAME ctr_encrypt_Pipeline_60 MODELNAME ctr_encrypt_Pipeline_60 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_60}
  {SRCNAME ctr_encrypt_Pipeline_61 MODELNAME ctr_encrypt_Pipeline_61 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_61}
  {SRCNAME ctr_encrypt_Pipeline_62 MODELNAME ctr_encrypt_Pipeline_62 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_62}
  {SRCNAME ctr_encrypt_Pipeline_loop_ctr_xor_block15 MODELNAME ctr_encrypt_Pipeline_loop_ctr_xor_block15 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_loop_ctr_xor_block15}
  {SRCNAME ctr_encrypt_Pipeline_64 MODELNAME ctr_encrypt_Pipeline_64 RTLNAME pynqrypt_encrypt_ctr_encrypt_Pipeline_64}
  {SRCNAME ctr_encrypt MODELNAME ctr_encrypt RTLNAME pynqrypt_encrypt_ctr_encrypt
    SUBMODULES {
      {MODELNAME pynqrypt_encrypt_ctr_encrypt_block_nonce_RAM_AUTO_1R1W RTLNAME pynqrypt_encrypt_ctr_encrypt_block_nonce_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pynqrypt_encrypt MODELNAME pynqrypt_encrypt RTLNAME pynqrypt_encrypt IS_TOP 1
    SUBMODULES {
      {MODELNAME pynqrypt_encrypt_pynqrypt_round_keys_RAM_AUTO_1R1W RTLNAME pynqrypt_encrypt_pynqrypt_round_keys_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pynqrypt_encrypt_pynqrypt_key_RAM_AUTO_1R1W RTLNAME pynqrypt_encrypt_pynqrypt_key_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pynqrypt_encrypt_pynqrypt_nonce_RAM_AUTO_1R1W RTLNAME pynqrypt_encrypt_pynqrypt_nonce_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pynqrypt_encrypt_gmem_m_axi RTLNAME pynqrypt_encrypt_gmem_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME pynqrypt_encrypt_control_s_axi RTLNAME pynqrypt_encrypt_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
