// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pynqrypt_encrypt_pynqrypt_encrypt,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020i-clg400-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=8,HLS_SYN_DSP=0,HLS_SYN_FF=5407,HLS_SYN_LUT=52939,HLS_VERSION=2022_2}" *)

module pynqrypt_encrypt (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 128;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (128 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [127:0] key;
wire   [95:0] nonce;
wire   [63:0] plaintext_length;
wire   [63:0] plaintext;
wire   [63:0] ciphertext;
reg   [63:0] ciphertext_read_reg_253;
reg   [63:0] plaintext_read_reg_258;
reg   [95:0] nonce_read_reg_263;
reg   [31:0] tmp_1_reg_268;
wire   [31:0] trunc_ln628_fu_239_p1;
reg   [31:0] trunc_ln628_reg_273;
reg   [59:0] trunc_ln1_reg_278;
reg   [5:0] p_round_key_V_address0;
reg    p_round_key_V_ce0;
reg    p_round_key_V_we0;
reg   [31:0] p_round_key_V_d0;
wire   [31:0] p_round_key_V_q0;
reg   [5:0] p_round_key_V_address1;
reg    p_round_key_V_ce1;
reg    p_round_key_V_we1;
reg   [31:0] p_round_key_V_d1;
wire   [31:0] p_round_key_V_q1;
reg   [3:0] pynqrypt_round_keys_V_address0;
reg    pynqrypt_round_keys_V_ce0;
reg    pynqrypt_round_keys_V_we0;
wire   [127:0] pynqrypt_round_keys_V_q0;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_done;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_idle;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_ready;
wire   [5:0] grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_address0;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_ce0;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_we0;
wire   [31:0] grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_d0;
wire   [5:0] grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_address1;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_ce1;
wire    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_we1;
wire   [31:0] grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_d1;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_done;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_idle;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_ready;
wire   [5:0] grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_address0;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_ce0;
wire   [5:0] grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_address1;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_ce1;
wire   [3:0] grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_address0;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_ce0;
wire    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_we0;
wire   [127:0] grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_d0;
wire   [3:0] grp_ctr_encrypt_fu_192_this_round_keys_address0;
wire    grp_ctr_encrypt_fu_192_this_round_keys_ce0;
wire   [127:0] grp_ctr_encrypt_fu_192_this_round_keys_d0;
wire    grp_ctr_encrypt_fu_192_this_round_keys_we0;
wire   [3:0] grp_ctr_encrypt_fu_192_this_round_keys_address1;
wire    grp_ctr_encrypt_fu_192_this_round_keys_ce1;
wire   [127:0] grp_ctr_encrypt_fu_192_this_round_keys_d1;
wire    grp_ctr_encrypt_fu_192_this_round_keys_we1;
wire    grp_ctr_encrypt_fu_192_m_axi_gmem_AWVALID;
wire   [63:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWADDR;
wire   [0:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWID;
wire   [31:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWLEN;
wire   [2:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWSIZE;
wire   [1:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWBURST;
wire   [1:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWLOCK;
wire   [3:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWCACHE;
wire   [2:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWPROT;
wire   [3:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWQOS;
wire   [3:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWREGION;
wire   [0:0] grp_ctr_encrypt_fu_192_m_axi_gmem_AWUSER;
wire    grp_ctr_encrypt_fu_192_m_axi_gmem_WVALID;
wire   [127:0] grp_ctr_encrypt_fu_192_m_axi_gmem_WDATA;
wire   [15:0] grp_ctr_encrypt_fu_192_m_axi_gmem_WSTRB;
wire    grp_ctr_encrypt_fu_192_m_axi_gmem_WLAST;
wire   [0:0] grp_ctr_encrypt_fu_192_m_axi_gmem_WID;
wire   [0:0] grp_ctr_encrypt_fu_192_m_axi_gmem_WUSER;
wire    grp_ctr_encrypt_fu_192_m_axi_gmem_ARVALID;
wire   [63:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARADDR;
wire   [0:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARID;
wire   [31:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARLEN;
wire   [2:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARSIZE;
wire   [1:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARBURST;
wire   [1:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARLOCK;
wire   [3:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARCACHE;
wire   [2:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARPROT;
wire   [3:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARQOS;
wire   [3:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARREGION;
wire   [0:0] grp_ctr_encrypt_fu_192_m_axi_gmem_ARUSER;
wire    grp_ctr_encrypt_fu_192_m_axi_gmem_RREADY;
wire    grp_ctr_encrypt_fu_192_m_axi_gmem_BREADY;
wire    grp_ctr_encrypt_fu_192_ap_start;
wire    grp_ctr_encrypt_fu_192_ap_done;
wire    grp_ctr_encrypt_fu_192_ap_ready;
wire    grp_ctr_encrypt_fu_192_ap_idle;
reg    grp_ctr_encrypt_fu_192_ap_continue;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [127:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_ctr_encrypt_fu_192_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_sync_grp_ctr_encrypt_fu_192_ap_ready;
wire    ap_sync_grp_ctr_encrypt_fu_192_ap_done;
reg    ap_block_state8_on_subcall_done;
reg    ap_sync_reg_grp_ctr_encrypt_fu_192_ap_ready;
reg    ap_sync_reg_grp_ctr_encrypt_fu_192_ap_done;
wire    ap_CS_fsm_state2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start_reg = 1'b0;
#0 grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start_reg = 1'b0;
#0 grp_ctr_encrypt_fu_192_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_ctr_encrypt_fu_192_ap_ready = 1'b0;
#0 ap_sync_reg_grp_ctr_encrypt_fu_192_ap_done = 1'b0;
end

pynqrypt_encrypt_p_round_key_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 44 ),
    .AddressWidth( 6 ))
p_round_key_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(p_round_key_V_address0),
    .ce0(p_round_key_V_ce0),
    .we0(p_round_key_V_we0),
    .d0(p_round_key_V_d0),
    .q0(p_round_key_V_q0),
    .address1(p_round_key_V_address1),
    .ce1(p_round_key_V_ce1),
    .we1(p_round_key_V_we1),
    .d1(p_round_key_V_d1),
    .q1(p_round_key_V_q1)
);

pynqrypt_encrypt_pynqrypt_round_keys_V_RAM_AUTO_1R1W #(
    .DataWidth( 128 ),
    .AddressRange( 11 ),
    .AddressWidth( 4 ))
pynqrypt_round_keys_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(pynqrypt_round_keys_V_address0),
    .ce0(pynqrypt_round_keys_V_ce0),
    .we0(pynqrypt_round_keys_V_we0),
    .d0(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_d0),
    .q0(pynqrypt_round_keys_V_q0)
);

pynqrypt_encrypt_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start),
    .ap_done(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_done),
    .ap_idle(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_idle),
    .ap_ready(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_ready),
    .p_round_key_V_address0(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_address0),
    .p_round_key_V_ce0(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_ce0),
    .p_round_key_V_we0(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_we0),
    .p_round_key_V_d0(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_d0),
    .p_round_key_V_q0(p_round_key_V_q0),
    .p_round_key_V_address1(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_address1),
    .p_round_key_V_ce1(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_ce1),
    .p_round_key_V_we1(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_we1),
    .p_round_key_V_d1(grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_d1),
    .p_round_key_V_q1(p_round_key_V_q1)
);

pynqrypt_encrypt_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1 grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start),
    .ap_done(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_done),
    .ap_idle(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_idle),
    .ap_ready(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_ready),
    .p_round_key_V_address0(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_address0),
    .p_round_key_V_ce0(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_ce0),
    .p_round_key_V_q0(p_round_key_V_q0),
    .p_round_key_V_address1(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_address1),
    .p_round_key_V_ce1(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_ce1),
    .p_round_key_V_q1(p_round_key_V_q1),
    .pynqrypt_round_keys_V_address0(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_address0),
    .pynqrypt_round_keys_V_ce0(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_ce0),
    .pynqrypt_round_keys_V_we0(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_we0),
    .pynqrypt_round_keys_V_d0(grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_d0)
);

pynqrypt_encrypt_ctr_encrypt grp_ctr_encrypt_fu_192(
    .p_read(nonce_read_reg_263),
    .this_round_keys_address0(grp_ctr_encrypt_fu_192_this_round_keys_address0),
    .this_round_keys_ce0(grp_ctr_encrypt_fu_192_this_round_keys_ce0),
    .this_round_keys_d0(grp_ctr_encrypt_fu_192_this_round_keys_d0),
    .this_round_keys_q0(pynqrypt_round_keys_V_q0),
    .this_round_keys_we0(grp_ctr_encrypt_fu_192_this_round_keys_we0),
    .this_round_keys_address1(grp_ctr_encrypt_fu_192_this_round_keys_address1),
    .this_round_keys_ce1(grp_ctr_encrypt_fu_192_this_round_keys_ce1),
    .this_round_keys_d1(grp_ctr_encrypt_fu_192_this_round_keys_d1),
    .this_round_keys_q1(128'd0),
    .this_round_keys_we1(grp_ctr_encrypt_fu_192_this_round_keys_we1),
    .block_count(trunc_ln1_reg_278),
    .m_axi_gmem_AWVALID(grp_ctr_encrypt_fu_192_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_ctr_encrypt_fu_192_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_ctr_encrypt_fu_192_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_ctr_encrypt_fu_192_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_ctr_encrypt_fu_192_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_ctr_encrypt_fu_192_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_ctr_encrypt_fu_192_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_ctr_encrypt_fu_192_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_ctr_encrypt_fu_192_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_ctr_encrypt_fu_192_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_ctr_encrypt_fu_192_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_ctr_encrypt_fu_192_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_ctr_encrypt_fu_192_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_ctr_encrypt_fu_192_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_ctr_encrypt_fu_192_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_ctr_encrypt_fu_192_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_ctr_encrypt_fu_192_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_ctr_encrypt_fu_192_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_ctr_encrypt_fu_192_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_ctr_encrypt_fu_192_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_ctr_encrypt_fu_192_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_ctr_encrypt_fu_192_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_ctr_encrypt_fu_192_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_ctr_encrypt_fu_192_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_ctr_encrypt_fu_192_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_ctr_encrypt_fu_192_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_ctr_encrypt_fu_192_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_ctr_encrypt_fu_192_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_ctr_encrypt_fu_192_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_ctr_encrypt_fu_192_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_ctr_encrypt_fu_192_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_ctr_encrypt_fu_192_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .plaintext(plaintext_read_reg_258),
    .ciphertext(ciphertext_read_reg_253),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .plaintext_ap_vld(1'b1),
    .p_read_ap_vld(1'b1),
    .ciphertext_ap_vld(1'b1),
    .ap_start(grp_ctr_encrypt_fu_192_ap_start),
    .ap_done(grp_ctr_encrypt_fu_192_ap_done),
    .ap_ready(grp_ctr_encrypt_fu_192_ap_ready),
    .ap_idle(grp_ctr_encrypt_fu_192_ap_idle),
    .ap_continue(grp_ctr_encrypt_fu_192_ap_continue)
);

pynqrypt_encrypt_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .key(key),
    .nonce(nonce),
    .plaintext_length(plaintext_length),
    .plaintext(plaintext),
    .ciphertext(ciphertext),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

pynqrypt_encrypt_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 128 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(grp_ctr_encrypt_fu_192_m_axi_gmem_ARADDR),
    .I_ARLEN(grp_ctr_encrypt_fu_192_m_axi_gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(grp_ctr_encrypt_fu_192_m_axi_gmem_AWADDR),
    .I_AWLEN(grp_ctr_encrypt_fu_192_m_axi_gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_ctr_encrypt_fu_192_m_axi_gmem_WDATA),
    .I_WSTRB(grp_ctr_encrypt_fu_192_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_ctr_encrypt_fu_192_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_sync_reg_grp_ctr_encrypt_fu_192_ap_done <= 1'b0;
        end else if ((grp_ctr_encrypt_fu_192_ap_done == 1'b1)) begin
            ap_sync_reg_grp_ctr_encrypt_fu_192_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_ctr_encrypt_fu_192_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
            ap_sync_reg_grp_ctr_encrypt_fu_192_ap_ready <= 1'b0;
        end else if ((grp_ctr_encrypt_fu_192_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_ctr_encrypt_fu_192_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_ctr_encrypt_fu_192_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) | ((ap_sync_grp_ctr_encrypt_fu_192_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state8)))) begin
            grp_ctr_encrypt_fu_192_ap_start_reg <= 1'b1;
        end else if ((grp_ctr_encrypt_fu_192_ap_ready == 1'b1)) begin
            grp_ctr_encrypt_fu_192_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_ready == 1'b1)) begin
            grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_ready == 1'b1)) begin
            grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ciphertext_read_reg_253 <= ciphertext;
        nonce_read_reg_263 <= nonce;
        plaintext_read_reg_258 <= plaintext;
        tmp_1_reg_268 <= {{key[63:32]}};
        trunc_ln1_reg_278 <= {{plaintext_length[63:4]}};
        trunc_ln628_reg_273 <= trunc_ln628_fu_239_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state8_on_subcall_done)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_ARVALID = grp_ctr_encrypt_fu_192_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_AWVALID = grp_ctr_encrypt_fu_192_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_BREADY = grp_ctr_encrypt_fu_192_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_RREADY = grp_ctr_encrypt_fu_192_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        gmem_WVALID = grp_ctr_encrypt_fu_192_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
        grp_ctr_encrypt_fu_192_ap_continue = 1'b1;
    end else begin
        grp_ctr_encrypt_fu_192_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_round_key_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        p_round_key_V_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_round_key_V_address0 = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_address0 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_address0;
    end else begin
        p_round_key_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_round_key_V_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        p_round_key_V_address1 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_round_key_V_address1 = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_address1 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_address1;
    end else begin
        p_round_key_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        p_round_key_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_round_key_V_ce0 = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_ce0 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_ce0;
    end else begin
        p_round_key_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        p_round_key_V_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_round_key_V_ce1 = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_p_round_key_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_ce1 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_ce1;
    end else begin
        p_round_key_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_round_key_V_d0 = trunc_ln628_reg_273;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        p_round_key_V_d0 = {{key[95:64]}};
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_d0 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_d0;
    end else begin
        p_round_key_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_round_key_V_d1 = tmp_1_reg_268;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        p_round_key_V_d1 = {{key[127:96]}};
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_d1 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_d1;
    end else begin
        p_round_key_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        p_round_key_V_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_we0 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_we0;
    end else begin
        p_round_key_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        p_round_key_V_we1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_round_key_V_we1 = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_p_round_key_V_we1;
    end else begin
        p_round_key_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pynqrypt_round_keys_V_address0 = grp_ctr_encrypt_fu_192_this_round_keys_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pynqrypt_round_keys_V_address0 = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_address0;
    end else begin
        pynqrypt_round_keys_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        pynqrypt_round_keys_V_ce0 = grp_ctr_encrypt_fu_192_this_round_keys_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        pynqrypt_round_keys_V_ce0 = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_ce0;
    end else begin
        pynqrypt_round_keys_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pynqrypt_round_keys_V_we0 = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_pynqrypt_round_keys_V_we0;
    end else begin
        pynqrypt_round_keys_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b0 == ap_block_state8_on_subcall_done) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state8_on_subcall_done = ((ap_sync_grp_ctr_encrypt_fu_192_ap_ready & ap_sync_grp_ctr_encrypt_fu_192_ap_done) == 1'b0);
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_ctr_encrypt_fu_192_ap_done = (grp_ctr_encrypt_fu_192_ap_done | ap_sync_reg_grp_ctr_encrypt_fu_192_ap_done);

assign ap_sync_grp_ctr_encrypt_fu_192_ap_ready = (grp_ctr_encrypt_fu_192_ap_ready | ap_sync_reg_grp_ctr_encrypt_fu_192_ap_ready);

assign grp_ctr_encrypt_fu_192_ap_start = grp_ctr_encrypt_fu_192_ap_start_reg;

assign grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start = grp_pynqrypt_encrypt_Pipeline_VITIS_LOOP_181_1_fu_186_ap_start_reg;

assign grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start = grp_pynqrypt_encrypt_Pipeline_loop_aes_generate_round_keys_fu_179_ap_start_reg;

assign trunc_ln628_fu_239_p1 = key[31:0];


reg find_df_deadlock = 0;
// synthesis translate_off
`include "pynqrypt_encrypt_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //pynqrypt_encrypt

