// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pynqrypt_encrypt_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        plaintext_length,
        plaintext_length_c_din,
        plaintext_length_c_num_data_valid,
        plaintext_length_c_fifo_cap,
        plaintext_length_c_full_n,
        plaintext_length_c_write,
        plaintext,
        plaintext_c_din,
        plaintext_c_num_data_valid,
        plaintext_c_fifo_cap,
        plaintext_c_full_n,
        plaintext_c_write,
        ciphertext,
        ciphertext_c_din,
        ciphertext_c_num_data_valid,
        ciphertext_c_fifo_cap,
        ciphertext_c_full_n,
        ciphertext_c_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] plaintext_length;
output  [63:0] plaintext_length_c_din;
input  [2:0] plaintext_length_c_num_data_valid;
input  [2:0] plaintext_length_c_fifo_cap;
input   plaintext_length_c_full_n;
output   plaintext_length_c_write;
input  [63:0] plaintext;
output  [63:0] plaintext_c_din;
input  [2:0] plaintext_c_num_data_valid;
input  [2:0] plaintext_c_fifo_cap;
input   plaintext_c_full_n;
output   plaintext_c_write;
input  [63:0] ciphertext;
output  [63:0] ciphertext_c_din;
input  [2:0] ciphertext_c_num_data_valid;
input  [2:0] ciphertext_c_fifo_cap;
input   ciphertext_c_full_n;
output   ciphertext_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg plaintext_length_c_write;
reg plaintext_c_write;
reg ciphertext_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    plaintext_length_c_blk_n;
reg    plaintext_c_blk_n;
reg    ciphertext_c_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ciphertext_c_blk_n = ciphertext_c_full_n;
    end else begin
        ciphertext_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ciphertext_c_write = 1'b1;
    end else begin
        ciphertext_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        plaintext_c_blk_n = plaintext_c_full_n;
    end else begin
        plaintext_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        plaintext_c_write = 1'b1;
    end else begin
        plaintext_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        plaintext_length_c_blk_n = plaintext_length_c_full_n;
    end else begin
        plaintext_length_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        plaintext_length_c_write = 1'b1;
    end else begin
        plaintext_length_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ciphertext_c_full_n == 1'b0) | (plaintext_c_full_n == 1'b0) | (plaintext_length_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ciphertext_c_din = ciphertext;

assign plaintext_c_din = plaintext;

assign plaintext_length_c_din = plaintext_length;

endmodule //pynqrypt_encrypt_entry_proc
